name: Checks

on: [push]

jobs: 
  test-lint:
    name: Test and Lint
    runs-on: self-hosted #ubuntu-20.04 #
    steps:
      - name: Login To Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{  secrets.DOCKERHUB_USERNAME }}
          password: ${{  secrets.DOCKERHUB_TOKEN }}
      - name: checkout 
        uses: actions/checkout@v2
      - name: test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: linting
        run: docker-compose run --rm app sh -c "flake8"